# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame, QApplication, QMainWindow, QPlainTextEdit, QVBoxLayout, QWidget
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QTimer, QDateTime, QTime



class Ui_MainGui(object):


    def setupUi(self, MainGui):
        MainGui.setObjectName("MainGui")
        MainGui.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainGui.sizePolicy().hasHeightForWidth())
        MainGui.setSizePolicy(sizePolicy)
        MainGui.setMinimumSize(QtCore.QSize(1280, 720))
        MainGui.setMaximumSize(QtCore.QSize(1280, 720))
        MainGui.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Title = QtWidgets.QLabel(MainGui)
        self.Title.setGeometry(QtCore.QRect(40, 20, 1201, 81))
        self.Title.setStyleSheet("background-color: transparent;")
        self.Title.setText("")
        self.Title.setPixmap(QtGui.QPixmap("C:/Users/ASUS/OneDrive - Vivekananda Institute of Professional Studies/PROJECTS/Python/Gary 2.0 + UI/GUI resc/Title.png"))
        self.Title.setScaledContents(True)
        self.Title.setObjectName("Title")
        self.loading = QtWidgets.QLabel(MainGui)
        self.loading.setGeometry(QtCore.QRect(480, 100, 300, 300))
        self.loading.setText("")
        self.loading.setPixmap(QtGui.QPixmap("C:/Users/ASUS/OneDrive - Vivekananda Institute of Professional Studies/PROJECTS/Python/Gary 2.0 + UI/GUI resc/Loading.gif"))
        self.loading.setScaledContents(True)
        self.loading.setObjectName("loading")
        self.speaking = QtWidgets.QLabel(MainGui)
        self.speaking.setGeometry(QtCore.QRect(510, 120, 261, 251))
        self.speaking.setStyleSheet("background-color: transparent;")
        self.speaking.setText("")
        self.speaking.setPixmap(QtGui.QPixmap("C:/Users/ASUS/OneDrive - Vivekananda Institute of Professional Studies/PROJECTS/Python/Gary 2.0 + UI/GUI resc/AI Speaking.gif"))
        self.speaking.setScaledContents(True)
        self.speaking.setObjectName("speaking")
        self.listening = QtWidgets.QLabel(MainGui)
        self.listening.setGeometry(QtCore.QRect(500, 100, 281, 271))
        self.listening.setText("")
        self.listening.setPixmap(QtGui.QPixmap("C:/Users/ASUS/OneDrive - Vivekananda Institute of Professional Studies/PROJECTS/Python/Gary 2.0 + UI/GUI resc/Listening AI.gif"))
        self.listening.setScaledContents(True)
        self.listening.setObjectName("listening")
        self.sleeping = QtWidgets.QLabel(MainGui)
        self.sleeping.setGeometry(QtCore.QRect(470, 60, 341, 341))
        self.sleeping.setStyleSheet("background-color: transparent;")
        self.sleeping.setText("")
        self.sleeping.setPixmap(QtGui.QPixmap("C:/Users/ASUS/OneDrive - Vivekananda Institute of Professional Studies/PROJECTS/Python/Gary 2.0 + UI/GUI resc/Sleeping.gif"))
        self.sleeping.setScaledContents(True)
        self.sleeping.setObjectName("sleeping")
        self.astro = QtWidgets.QLabel(MainGui)
        self.astro.setGeometry(QtCore.QRect(870, 60, 231, 361))
        self.astro.setStyleSheet("background-color: transparent;")
        self.astro.setText("")
        self.astro.setPixmap(QtGui.QPixmap("C:/Users/ASUS/OneDrive - Vivekananda Institute of Professional Studies/PROJECTS/Python/Gary 2.0 + UI/GUI resc/astro mov.gif"))
        self.astro.setScaledContents(True)
        self.astro.setObjectName("astro")
        self.Planet = QtWidgets.QLabel(MainGui)
        self.Planet.setGeometry(QtCore.QRect(0, 400, 1281, 510))
        self.Planet.setStyleSheet("background-color: transparent;")
        self.Planet.setText("")
        self.Planet.setPixmap(QtGui.QPixmap("C:/Users/ASUS/OneDrive - Vivekananda Institute of Professional Studies/PROJECTS/Python/Gary 2.0 + UI/GUI resc/planet1.png"))
        self.Planet.setScaledContents(True)
        self.Planet.setObjectName("Planet")
        self.enter = QtWidgets.QPushButton(MainGui)
        self.enter.setGeometry(QtCore.QRect(1149, 678, 111, 31))
        self.enter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enter.setStyleSheet("border-image: url(C:/Users/ASUS/OneDrive - Vivekananda Institute of Professional Studies/PROJECTS/Python/Gary 2.0 + UI/GUI resc/button.png);\n"
"background-color: transparent;")
        self.enter.setText("")
        self.enter.setObjectName("enter")
        self.output = QtWidgets.QPlainTextEdit(MainGui)
        self.output.setGeometry(QtCore.QRect(20, 407, 1241, 265))
        self.output.setFrameStyle(QFrame.NoFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.output.setFont(font)
        self.output.setStyleSheet("background-color: transparent;\n"
"color: white;")
        self.output.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.output.textChanged.connect(self.scroll)
        self.output.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.input = QtWidgets.QTextEdit(MainGui)
        self.input.setGeometry(QtCore.QRect(20, 680, 1131, 31))
        self.input.setFrameStyle(QFrame.NoFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.input.setFont(font)
        self.input.setStyleSheet("background-color: transparent;\n"
"color: white;")
        self.input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.input.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.input.setObjectName("input")
        self.response = QtWidgets.QLabel(MainGui)
        self.response.setGeometry(QtCore.QRect(13, 385, 1250, 331))
        self.response.setStyleSheet("background-color: transparent;")
        self.response.setText("")
        self.response.setPixmap(QtGui.QPixmap("C:/Users/ASUS/OneDrive - Vivekananda Institute of Professional Studies/PROJECTS/Python/Gary 2.0 + UI/GUI resc/textbox2.png"))
        self.response.setScaledContents(True)
        self.response.setObjectName("response")
        self.rocket = QtWidgets.QLabel(MainGui)
        self.rocket.setGeometry(QtCore.QRect(0, 0, 1281, 721))
        self.rocket.setText("")
        self.rocket.setPixmap(QtGui.QPixmap("C:/Users/ASUS/OneDrive - Vivekananda Institute of Professional Studies/PROJECTS/Python/Gary 2.0 + UI/GUI resc/rocket up down.gif"))
        self.rocket.setScaledContents(True)
        self.rocket.setObjectName("rocket")
        self.Time = QtWidgets.QPlainTextEdit(MainGui)
        self.Time.setGeometry(QtCore.QRect(573, 192, 160, 70))
        self.Time.setFrameStyle(QFrame.NoFrame)
        self.Time.setReadOnly(True)
        #font = QtGui.QFont()
        #font.setFamily("DS-Digital")
        #font.setPointSize(48)
        #font.setBold(True)
        self.Time.setFont(font)
        self.Time.setStyleSheet("background-color: transparent;")
        self.Time.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Time.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Time.setObjectName("Time")
        self.rocket.raise_()
        self.astro.raise_()
        self.loading.raise_()
        self.listening.raise_()
        self.speaking.raise_()
        self.sleeping.raise_()
        self.Planet.raise_()
        self.Title.raise_()
        self.response.raise_()
        self.enter.raise_()
        self.output.raise_()
        self.input.raise_()
        self.Time.raise_()

        self.retranslateUi(MainGui)
        QtCore.QMetaObject.connectSlotsByName(MainGui)


    def scroll(self):
        self.output.verticalScrollBar().setValue(self.output.verticalScrollBar().maximum())
    def retranslateUi(self, MainGui):
        _translate = QtCore.QCoreApplication.translate
        MainGui.setWindowTitle(_translate("MainGui", "Gary Desktop Assistant"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setWindowIcon(QIcon(r'C:\Users\ASUS\OneDrive - Vivekananda Institute of Professional Studies\PROJECTS\Python\Gary 2.0 + UI\GUI resc\gary final icon.ico'))
    MainGui = QtWidgets.QWidget()
    ui = Ui_MainGui()
    ui.setupUi(MainGui)
    MainGui.show()
    sys.exit(app.exec_())
